rstudio/shinycoreci

.Rbuildignore, .github/workflows/readme-rmd.yml, R/sysinfo.R, R/test_shinyjster.R, R/utils.R, README.Rmd, README.md, man/test_shinyjster.Rd, man/trigger.Rd, man/write_sysinfo.Rd
* Make sure the readme is always up to date
=> Use a README.Rmd that points to all the installed remotes

R/test_shinyjster.R, R/test_shinyjster_source.R, man/test_shinyjster.Rd
Related PR: https://github.com/schloerke/shinyjster/pull/21
=> pass browser into shinyjster code

R/test_in_external.R
Open shinyjster test (if possible) in a new tab.
=> Add a jster button to the browser viewer

R/test_app.R, man/test_shinyjster_app.Rd
This would allow for chrome to be tested with a specific dimension value. Ex:
```r
test_shinyjster_app("chrome", dimensions = "800x1600")
```
=> `test_shinyjster_app()` should accept `timeout` and `dimensions` to help create `browser_func`

R/test_app.R, R/view_test_images.R
Needed for https://github.com/rstudio/shinycoreci-apps/pull/73
=> Small improvements

R/deps_exact.R
If A installs B and B installs A, this is a valid order.
If A installs B and B installs A', then make sure A is installed after B.
=> Loosen restrictions on remote installation

R/docker.R, man/docker.Rd
Connected to https://github.com/rstudio/shinycoreci-apps/issues/157
=> Add R 4.1 version to sso and ssp runs

.github/workflows/R-CMD-check.yml, .github/workflows/rituals.yml, R/docker.R, R/rspm.R, R/test_in_sso.R, man/docker.Rd, man/rspm_install.Rd, man/test_in_ssossp.Rd
Which is needed to create the docker files in https://github.com/rstudio/shinycoreci-apps/pull/160
=> Allow focal in docker executions

R/test_in_connect.R, man/test_in_deployed.Rd
This is under the account "barret" on "beta.rstudioconnect.com".
=> Use the `urls` value that matches where apps are deployed

.github/internal/install-shinyverse/action.yaml, .github/workflows/apps-test-os.yml, .gitignore, inst/apps/012-datatables/tests/testthat/test-mytest.R, inst/apps/022-unicode-chinese/server.R, inst/apps/022-unicode-chinese/tests/testthat/test-mytest.R, inst/apps/027-absolutely-positioned-panels/ui.R, inst/apps/063-superzip-example/global.R, inst/apps/063-superzip-example/styles.css, inst/apps/114-modal-dialog/app.R, inst/apps/215-bslib-nav/app.R, todo.md
cc @MadhulikaTanuboddi 
Changes:
=> Fix a handful of apps to create consistent screenshots

inst/apps/218-insert-ui-jquery/app.R, inst/apps/218-insert-ui-jquery/tests/testthat.R, inst/apps/218-insert-ui-jquery/tests/testthat/setup.R, inst/apps/218-insert-ui-jquery/tests/testthat/test-shinytest2.R
Ported from https://github.com/rstudio/shinycoreci-apps/pull/206
* Translated test from shinyjster to shinytest2. 
* Added conditionalPanels to display if the test is passing or not when run manually
* Added title on what is expected
=> Add app to test rstudio/shiny#3630

inst/apps/209-set-current-theme/app.R, inst/apps/209-set-current-theme/tests/testthat/test-shinyjster.R
=> Assume bg is white if it's transparent

inst/apps/187-navbar-collapse/tests/testthat/test-shinyjster.R
=> Skip IE on 187

inst/apps/220-execute-hidden-plot/app.R, inst/apps/220-execute-hidden-plot/tests/testthat.R, inst/apps/220-execute-hidden-plot/tests/testthat/setup.R, inst/apps/220-execute-hidden-plot/tests/testthat/test-shinyjster.R
https://github.com/rstudio/shiny/pull/3740
=> Add a test for rstudio/shiny#3740

inst/apps/221-async-script-dynamic-ui/app.R, inst/apps/221-async-script-dynamic-ui/tests/testthat.R, inst/apps/221-async-script-dynamic-ui/tests/testthat/setup.R, inst/apps/221-async-script-dynamic-ui/tests/testthat/test-shinyjster.R
This is a test app for https://github.com/rstudio/shiny/pull/3666.
=> Add 221-async-script-dynamic-ui

inst/apps/306-accordion-add-remove/app.R
To address changes made in https://github.com/rstudio/bslib/pull/534
=> Set 0 padding on 306's page_fillable()

inst/apps/310-bslib-sidebar-dynamic/app.R, inst/apps/311-bslib-sidebar-toggle-methods/app.R
Fixes a trailing comma syntax error I introduced in #170
=> Fix trailing comma syntax error in 310-311

inst/apps/316-bslib-popovers/tests/testthat/test-316-bslib-popovers.R
Trying to help with the flakiness of 316 on Linux.
=> tests(316): Small tweaks to attempt to reduce flakiness

.github/workflows/apps-config.yml
Should fix the homebrew install errors we started seeing a few days ago https://github.com/rstudio/shinycoreci/actions/runs/6766515451/job/18388307439#step:12:598
https://rstudio.github.io/shinycoreci/results/2023/11/06/
=> Update to macos-12

.github/workflows/apps-deps.yml, .github/workflows/apps-test-os.yml, inst/apps/002-text/app.R
=> Github push failure should not prevent rebasing and trying again

inst/apps/227-persistent-progress/app.R, inst/apps/227-persistent-progress/test.js, inst/apps/227-persistent-progress/tests/testthat.R, inst/apps/227-persistent-progress/tests/testthat/setup.R, inst/apps/227-persistent-progress/tests/testthat/test-shinyjster.R
Tests for https://github.com/rstudio/shiny/pull/3954. Do not merge until that PR is merged.
=> Integration tests for the 'persistent progress' feature

README.Rmd, README.md
=> Mention `create_github_token()` instead of `browse_github_pat()`

README.Rmd, README.md
In continuing [previous commit](https://github.com/rstudio/shinycoreci/commit/16a6163a9c97b51ef82557a05bba959614734adb) of deploy testing apps external link.
=> docs(README): recent external link caption

inst/apps/200-flexdashboard-render-text/index.Rmd, inst/apps/200-flexdashboard-render-text/tests/testthat/test-shinyjster.R
This pull request includes updates to improve the accuracy of text comparison in tests and adjust test skipping behavior based on operating system.
=> fix(test): Unskip 200 flex
