rstudio/shinycoreci

R/app_status.R

Fixes `Error in system: 'cd' not found` on Windows

Avoid system cd call

---

R/deps_exact.R

Fixes situation where
```
github:shinycoreci -> github:flexdashboard
github:shinycoreci -> cran:rmarkdown
github:flexdashboard -> github:rmarkdown
```

Reinstall parent package if GitHub Remotes are installed from CRAN

---

R/app_status.R

`git fetch` will say "you are behind by 5 commits". This is bad as I don't want the disk to be behind.  It should be updated

Use git pull, not git fetch, to make sure the disk is the latest version

---

R/test_runtests.R

this child process wasn't respecting the options set in the parent process

pass in the install.packages.check.source option to the child proc

---

DESCRIPTION
R/test_runtests.R
README.md

Helps for older R versions trying to update pkgs like `rlang`.

Use `pkgdepends` to find the full install tree

---

.Rbuildignore
R/fix_all_gha_branches.R
man/fix_all_gha_branches.Rd

Fixes https://github.com/rstudio/shinycoreci/issues/61
* Rename `merge` / `commit` to `save_results = NULL` (which asks by default)
* If `save_result = FALSE`, all app folder changes will be reset before moving on
* Split `ask` into `ask_apps = TRUE` and `ask_branches = FALSE`
* Add `ask_if_not_master` branch support
* Use an internal data.frame for easier ordering / subsetting

Add support for asking for branches and apps before fixing

---

DESCRIPTION
R/utils.R
README.md

Should resolve error: https://github.com/rstudio/shinycoreci-apps/runs/2181707322?check_suite_focus=true
```
2021-03-24T07:12:23.2879560Z 211-sv-custom-inputs [============================] 1/1 eta: 0s elapsed: 0s
2021-03-24T07:12:23.2880460Z 
2021-03-24T07:12:23.5942000Z Preparing to deploy application...DONE
2021-03-24T07:12:25.1419120Z Uploading bundle for application: 3787325...Error : Unable to retrieve package records for the following packages:
2021-03-24T07:12:25.1421500Z - 'shinyvalidate'
2021-03-24T07:12:25.1422700Z In addition: Warning message:
2021-03-24T07:12:25.1423570Z In FUN(X[[i]], ...) :
2021-03-24T07:12:25.1425130Z   Package 'shinyvalidate' not available in repository or locally
2021-03-24T07:12:25.1426100Z 
2021-03-24T07:12:25.1427320Z Warning message: …
```

Add in shinyvalidate remote pkg

---

inst/view_test_diff/app.R

Related: #68 
* Circles for results
* Okabe ito colors
* Do not have platform be dynamic. Only append platforms
* Safeguard spread operation
Updated colors and through colorblind simulation

Followup updates `view_test_results()`

---

DESCRIPTION
R/fix_all_gha_branches.R
man/fix_all_gha_branches.Rd

This is not recommended in regular practice. Only use when diffs can not be displayed and you want to blindly accept the changes.

Add parameter to accept all shinytest changes (Not recommended)

---

R/test_app.R

For 10+ days, mac tests have not been able to complete. No known change was made to cause this.
For now, disabling the mac firefox tests.
cc @MadhulikaTanuboddi 
----------------
Ex output: https://github.com/rstudio/shinycoreci-apps/runs/3723131787?check_suite_focus=true#step:32:1407
```
[89/377; 2h; 6h] 123-async-renderprint ~ shinyjster-firefox.R
Loading required package: shiny
shinyjster - starting app: 123-async-renderprint
Warning: Warning: Strategy 'multiprocess' is deprecated in future (>= 1.20.0). Instead, explicitly specify either 'multisession' or 'multicore'. In the current R session, 'multiprocess' equals 'multicore'.
Listening on http://127.0.0.1:45939
Running java -jar \
/Users/runner/work/_temp/Library/shinyjster/selenium/selenium.jar firefox \
1200x1200 …
```

Temporarily Do not test `shinyjster` mac firefox tests

---

inst/apps/012-datatables/tests/testthat/test-mytest.R
inst/apps/014-onflushed/tests/testthat/test-mytest.R
inst/apps/019-mathjax/tests/testthat/test-mytest.R
inst/apps/020-knit-html/tests/testthat/test-mytest.R
inst/apps/026-shiny-inline/tests/testthat/test-mytest.R
inst/apps/054-nvd3-line-chart-output/tests/testthat/test-mytest.R
inst/apps/082-word-cloud/tests/testthat/test-mytest.R
inst/apps/114-modal-dialog/tests/testthat/test-mytest.R
inst/apps/117-shinythemes/tests/testthat/test-mytest.R
inst/apps/118-highcharter-births/tests/testthat/test-mytest.R
inst/apps/119-namespaced-conditionalpanel-demo/tests/testthat/test-mytest.R
inst/apps/122-async-outputs/tests/testthat/test-mytest.R
inst/apps/123-async-renderprint/tests/testthat/test-mytest.R
inst/apps/125-async-req/tests/testthat/test-mytest.R
inst/apps/135-bookmark-uioutput/tests/testthat/test-mytest.R
inst/apps/137-plot-cache-key/app.R
inst/apps/142-reactive-timer/app.R
inst/apps/149-onRender/tests/testthat/test-mytest.R
inst/apps/150-networkD3-sankey/tests/testthat/test-mytest.R
inst/apps/151-reactr-input/tests/testthat/test-mytest.R
inst/apps/156-subapps/tests/testthat/test-mytest.R
inst/apps/190-reactlog-module-ex1/tests/testthat/test-mytest.R
inst/apps/191-reactlog-pythagoras/tests/testthat/test-mytest.R
inst/apps/192-reactlog-hello/tests/testthat/test-mytest.R
inst/apps/193-reactlog-dynamic-ui/tests/testthat/test-mytest.R
inst/apps/194-plot-cache-key/app.R
inst/apps/194-plot-cache-key/tests/testthat/test-mytest.R
inst/apps/200-flexdashboard-render-text/tests/testthat/test-mytest.R
inst/apps/303-bslib-html-template/tests/testthat/test-mytest.R

cc @MadhulikaTanuboddi 
Changed app 122 from a fixed sleep length to a `app$wait_for_idle()`. Then went through all other apps with a call to `Sys.sleep()` and changed them to `$wait_for_idle()` or added a comment on why the sleep is there.

Change from fixed time sleep to `$wait_for_idle()` where possible

---

inst/apps/093-plot-interaction-basic/app.R
inst/apps/094-image-interaction-basic/app.R
inst/apps/096-plot-interaction-article-1/app.R
inst/apps/097-plot-interaction-article-2/app.R
inst/apps/098-plot-interaction-article-3/app.R
inst/apps/099-plot-interaction-article-4/app.R
inst/apps/100-plot-interaction-article-5/app.R
inst/apps/101-plot-interaction-article-6/app.R
inst/apps/102-plot-interaction-article-7/app.R
inst/apps/103-plot-interaction-article-8/app.R
inst/apps/104-plot-interaction-select/app.R
inst/apps/105-plot-interaction-zoom/app.R
inst/apps/106-plot-interaction-exclude/app.R

Following upon https://github.com/rstudio/shinycoreci/commit/c198ecb410ec70521ac6626c7a116bb1a3304938, the GHA test runs started failing due to errors from "inst/gha/validate-test-files.R"
This is happening especially with any of the plot interaction based apps because these apps does not have any automated tests and from the commit above, we marked them as non-manual tests (in other words automated) just to have these apps not show up in our "shinycoreci::test_in_<xyz>" functions (when the team does the release testing). However, that caused the GHA test builds to fail because the validate script mentioned above looks for "tests" folder for any non-manual app.
Ref: https://github.com/rstudio/shinycoreci/runs/7174522879?check_suite_focus=true
So, we decided to revert the changes for only …

Add the plot interaction apps back to the manual list

---

R/data-apps-deps.R
inst/apps/306-accordion-add-remove/app.R
inst/apps/306-accordion-add-remove/tests/testthat.R
inst/apps/306-accordion-add-remove/tests/testthat/setup-shinytest2.R
inst/apps/306-accordion-add-remove/tests/testthat/test-shinytest2.R
inst/apps/307-accordion-replace/app.R
inst/apps/307-accordion-replace/tests/testthat.R
inst/apps/307-accordion-replace/tests/testthat/setup.R
inst/apps/307-accordion-replace/tests/testthat/test-shinyjster.R

This PR adds two tests:
1. `306-accordion-add-remove`: This app primarily tests `accordion_panel_insert()`, `accordion_panel_remove()`, `accordion_panel_set()`, and `accordion_panel_open()`. It also takes screenshots (instead of testing markup) since it implicitly depends on compliance with Bootstrap markup. Note that we also use an `accordion()` inside a `sidebar()` here to ensure it renders flush with the sidebar.
2. `307-accordion-replace`: Primarily tests `accordion_panel_update()`

`bslib::accordion()` tests

---

DESCRIPTION
R/deploy-apps.R
R/deploy-connect-urls.R
R/install.R
R/sysinfo.R
R/test-in-ide.R
R/triple_colon.R
R/utils.R
inst/apps/001-hello/app.R
man/write_sysinfo.Rd
tests/testthat/test-sysinfo.R

Given `{renv}` 17, we get this error when saving the sys info
```
2023-03-23T06:57:39.7327400Z Stopping tests for app: 302-bootswatch-themes
2023-03-23T06:57:39.7328110Z ###
2023-03-23T06:57:40.2999050Z Error in triple_colon("renv", "renv_snapshot_r_packages")(...) : 
2023-03-23T06:57:40.2999910Z   attempt to apply non-function
2023-03-23T06:57:40.3000540Z Calls: <Anonymous> -> <Anonymous>
```
`renv:::renv_snapshot_r_packages()` no longer exists.
I finally shot myself in the foot. 🦶 🔫

Use `{sessioninfo}` to save sysinfo files

---

inst/apps/024-optgroup-selectize/server.R
inst/apps/024-optgroup-selectize/ui.R

With the current example code, users may run into this issue: https://github.com/rstudio/shiny/issues/3706
This change will direct people away from writing code like that.

Use `list()` instead of `c()` for option groups in `selectizeInput`

---

inst/apps/301-bs-themes/app.R
inst/apps/302-bootswatch-themes/app.R

See https://github.com/rstudio/bslib/pull/572
Note that `300-bs-themer` also uses `themer-demo`, but it's fine to have that one use the latest version of the demo app since it's a manual test

Leverage themer-demo's env var to get legacy version of demo app

---

inst/apps/306-accordion-add-remove/app.R

Modifies `306` to gain some coverage of [#588](https://github.com/rstudio/bslib/pull/588). Note `310` and `311` have some tests that are more specific to `layout_sidebar()`.

Incorporate the new `page_sidebar()` into `306`

---

inst/apps/313-bslib-card-tab-focus/tests/testthat/test-313-bslib-card-tab-focus.R

Fixes #192 
After rstudio/bslib#669, all full screen capable cards have `data-full-screen="false"`, which is updated to `"true"` when the card is expanded.
This PR updates the tests to use this new slector.

tests(313): Fix bslib full screen card selector

---

inst/apps/313-bslib-card-tab-focus/tests/testthat/test-313-bslib-card-tab-focus.R

Updates the selector for the card full screen toggle button, the structure of which was changed in https://github.com/rstudio/bslib/pull/662.
Fixes #195

fix(313-bslib-card-tab-focus): Update selector for card full screen toggle button

---

inst/apps/314-bslib-tooltips/app.R
inst/apps/314-bslib-tooltips/tests/testthat.R
inst/apps/314-bslib-tooltips/tests/testthat/setup-shinytest2.R
inst/apps/314-bslib-tooltips/tests/testthat/test-314-bslib-tooltips.R

Adds tests for https://github.com/rstudio/bslib/pull/662

Add 314 - Unit tests for `bslib::tooltip()`

---

inst/apps/315-bslib-input-switch/README.md
inst/apps/315-bslib-input-switch/app.R
inst/apps/315-bslib-input-switch/tests/testthat.R
inst/apps/315-bslib-input-switch/tests/testthat/setup-shinytest2.R
inst/apps/315-bslib-input-switch/tests/testthat/test-315-bslib-input-switch.R

Adds tests around `bslib::input_switch()` and update methods
* https://github.com/rstudio/bslib/pull/483
* https://github.com/rstudio/bslib/issues/676

Add 315-bslib-input-switch

---

R/deploy-apps.R
README.md

Recently we ran into a case where deploy errors were not getting reported by `deploy_apps()`. This is a (untested) fix for what we think was happening (`deploy_res` can possibly be of length 0?)

more-careful-deploy-error-reporting

---

inst/apps/306-accordion-add-remove/app.R

Merging since this'll fix up some stylistic things, but it should still fail (for now) until [#3889](https://github.com/rstudio/shiny/issues/3889) is fixed

Also set default colors for the accordion's active button

---

inst/apps/309-flexdashboard-tabs-navs/tests/testthat/test-309-flexdashboard-tabs-navs.R

https://github.com/rstudio/bslib/pull/845 changes the breakpoint at which the navbar collapses in BS5, but these tests assumed the screen was wide enough to see the full navbar.
Fixes #228

fix(309): Use wide-enough screen size

---

render-results.Rmd

This PR changes the `<details>` elements used for test result logs to be closed by default. They'll still open if you click on the red bubbles, but I find it's much easier to orient myself to the problems in a particular test when I can see the structure (which variants are failing) before opening up a variant to zoom in.
| Closed | Open |
|:---:|:---:|
| ![rstudio_shinycoreci results_ 2023-10-14 - 2023-10-24 (1)](https://github.com/rstudio/shinycoreci/assets/5420529/c5d99272-e02f-4cca-8948-7815da1135cb) | ![rstudio_shinycoreci results_ 2023-10-14 - 2023-10-24](https://github.com/rstudio/shinycoreci/assets/5420529/02d5a3d8-cf9a-4820-825b-1b3a8d1f91b8) |

feat(render-results): Close all result logs by default

---

R/test-in-browser.R
R/test-in-sso.R

Fixes one instance where `any(nzchar())` is needed (missing `any()`) and then switches to `nzchar()` over `nchar()`.

fix: Use `any(nzchar(x))` instead of `nchar(x) > 0`

---

DESCRIPTION
R/accept_snaps.R
R/apps.R
R/fix_snaps.R
R/save-test-results.R
R/test-in-local.R
R/view-test-images.R
man/accept_snaps.Rd
man/fix_snaps.Rd
man/test-results.Rd
man/test_in_local.Rd
man/view_test_images.Rd

Fixes https://github.com/rstudio/shinycoreci/issues/234
The builds are failing though :(

Should stop execution if it can't find .inst/apps

---

inst/Docker/ubuntu_ssp/Dockerfile

Trying to fix failing builds: https://github.com/rstudio/shinycoreci/actions/runs/6710699582

docker(ssp): Add more cases for aws build machine envvar

---

.github/workflows/apps-test-matrix.yml

This temporary change is intended just to get the `r-release` tests running on Mac.
R 4.3.2 was released just yesterday, and the [binaries for Mac aren't yet available](https://cran.r-project.org/bin/macosx/)

Get r-release mac running again

---

.github/workflows/apps-config.yml
README.Rmd
README.md

We're seeing snapshot changes because of rolling updates to the underlying image, so this adds badges to the readme to make this easier to discover/check.

docs(readme): Add badges for github runner status

---

inst/apps/316-bslib-popovers/app.R
inst/apps/316-bslib-popovers/tests/testthat/test-316-bslib-popovers.R

Pairs with https://github.com/rstudio/bslib/pull/1017

Fix 316 and also make the `update_popover()` tests more exhaustive

---

DESCRIPTION
R/fix_snaps.R

Ran into this when trying to debug errors in the `git apply` call in `fix_snaps()`. When debugging `git diff` was capturing changes I had made to `R/`, which was causing more errors in `git apply`, and isn't relevant for snapshots

Only capture differences to inst/apps when generating patch files in fix_snaps()

---

.github/internal/install-shinyverse/action.yaml
inst/apps/001-hello/app.R

Currently mac takes 3+ hours to install. This is too long.
By removing `terra` which installs `gdal` with `brew`, install time should be faster. 
Leaflet apps may break. 🤷

Remove static mac deps to be installed

---

.github/workflows/apps-config.yml
.github/workflows/apps-test-matrix.yml
.github/workflows/apps-test-os.yml
.github/workflows/apps-test-precheck.yml

As of this commit...
* Ubuntu is migrating from `ubuntu-20` -> `ubuntu-latest`/`ubuntu-22`
* macos is migrating from `macos-12` -> `macos-latest`/`macos-14`
* The windows change is a no-op. `windows-latest` / `windows-2022`

Update os values to `macos-latest`, `ubuntu-latest`, and `windows-latest`

---

R/data-apps-deps.R
inst/apps/317-nav-insert/app.R
inst/apps/317-nav-insert/tests/testthat.R
inst/apps/317-nav-insert/tests/testthat/setup-shinytest2.R
inst/apps/317-nav-insert/tests/testthat/test-317-nav-insert.R
inst/apps/317-nav-insert/wc-init.js

Tests https://github.com/rstudio/shiny/pull/4179 and the additional cases the `shiny-insert-tab` message handler should cover in particular (from https://github.com/rstudio/shiny/pull/1794#issuecomment-318722200):
> We need these test cases for anywhere we insert dynamic UI:
> 
> 1. `<script>` blocks should run
> 2. `<script>` blocks should only run once
> 3. `head()`/`singleton()` should be respected
> 4. HTML widgets should work
> 	a. Even when the dependencies are not part of the initial page load
> 5. Shiny inputs/outputs should work
> 6. Subapps should work (include a `shinyApp` object right in the UI)
I also included a test that involves a custom element that modifies its attributes in its connected callback. For this kind of custom element, `shiny-insert-tab` would render the HTML …

tests: Add 317-nav-insert

---

DESCRIPTION
R/test-in-ide.R

Adds an internal helper function to quickly open an app and move into the app's working directory.
The purple code are clickable links that open the files directly. Note that you don't need to know the full app name, the app number is sufficient (thanks to existing helpers!).

feat: Add `ide_open_app()`

---

.github/workflows/apps-test-os.yml
DESCRIPTION

Downloads the latest stable release of `chrome-headless-shell` and then sets `CHROMOTE_CHROME` to that path so that it is used (for tests that rely on chromote) instead of the system installation of Chrome.

feat: Use `chrome-headless-shell` for chromote-based checks

---

inst/apps/158-input-labels/app.R

For https://github.com/rstudio/shiny/pull/3996

Update 158-input-labels to leverage HTML labels

---

inst/apps/314-bslib-tooltips/tests/testthat/test-314-bslib-tooltips.R

Replaces the generic ':last-child' selector with the specific '#btn3' selector in tooltip focus and visibility tests for improved accuracy.

Update selector in tooltip focus test
